<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.youdatax.main</groupId>
  <artifactId>youdatax-main-runtime</artifactId>
  <version>0.0.3.0</version>
  <name>yospace-core-common-runtime</name>
  <description>yospace-core-common-runtime</description>

  <dependencies>
<!--    api(project(":spi:common:core-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    api(project(":spi:common:encryption-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-encryption</artifactId> 
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":spi:common:http-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-http</artifactId> 
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":spi:common:transaction-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId> 
        <artifactId>yospace-core-spi-transaction</artifactId>   
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":spi:common:transaction-datasource-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi-transaction-datasource</artifactId>   
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    implementation(project(":core:common:lib:http-lib"))-->
      <dependency>
        <groupId>com.yospace.common</groupId>
        <artifactId>yospace-common-http-lib</artifactId> 
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    implementation(project(":core:common:lib:json-lib"))-->
      <dependency>
        <groupId>com.yospace.common</groupId>
        <artifactId>yospace-common-json-lib</artifactId>   
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    implementation(project(":core:common:lib:query-lib"))-->
       <dependency>
        <groupId>com.yospace.common</groupId>
        <artifactId>yospace-common-query-lib</artifactId>   
        <version>0.0.3-SNAPSHOT</version>
      </dependency>   
<!--    implementation(project(":core:common:lib:transform-lib"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-lib-transform</artifactId>  
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    implementation(project(":core:common:lib:validator-lib"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-lib-validator</artifactId> 
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    implementation(project(":core:common:lib:encryption-lib"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-lib-encryption</artifactId>  
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
            
<!--    testImplementation(project(":core:common:junit"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>junit</artifactId>
        <version>0.18.0</version>
        <scope>test</scope>
      </dependency>    
<!--    testImplementation(libs.awaitility)  
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }-->
      <dependency>
        <groupId>org.awaitility</groupId>
        <artifactId>awaitility</artifactId>
        <version>4.2.2</version>
        <scope>test</scope>
      </dependency>    
  </dependencies>  
</project>